# Generated by Django 4.1.5 on 2023-02-15 14:54

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="datetime_rules",
        ),
    ]
