# Generated by Django 4.1.5 on 2023-02-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import librephotos.mixins.clusters
import librephotos.mixins.faces
import librephotos.mixins.persons
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("librephotos", "0002_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mean_face_encoding", models.TextField()),
                ("cluster_id", models.IntegerField(null=True)),
                ("name", models.TextField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=models.SET(users.models.UserMixin.get_deleted_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(
                            librephotos.mixins.persons.PersonMixin.get_unknown_person
                        ),
                        related_name="clusters",
                        to="librephotos.person",
                    ),
                ),
            ],
            bases=(librephotos.mixins.clusters.ClusterMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="faces")),
                ("image_path", models.FilePathField()),
                ("person_label_is_inferred", models.BooleanField(null=True)),
                ("person_label_probability", models.FloatField(default=0.0)),
                ("location_top", models.IntegerField()),
                ("location_bottom", models.IntegerField()),
                ("location_left", models.IntegerField()),
                ("location_right", models.IntegerField()),
                ("encoding", models.TextField()),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(
                            librephotos.mixins.clusters.ClusterMixin.get_unknown_cluster
                        ),
                        related_name="faces",
                        to="librephotos.cluster",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="faces",
                        to="librephotos.person",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="librephotos.photo",
                    ),
                ),
            ],
            bases=(librephotos.mixins.faces.FaceMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="face",
            index=models.Index(
                fields=["person_label_is_inferred", "person_label_probability"],
                name="librephotos_person__ff1855_idx",
            ),
        ),
    ]
